version: '2'
services:

  db:
    image: mariadb:10.1
    container_name: bloodbank_DB
    restart: always
    volumes:
      - ./db/initdb/:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=111222333
      - MYSQL_DATABASE=bloodbank
      - MYSQL_USER=deshario
      - MYSQL_PASSWORD=123456

  app:
    build: ./app
    container_name: bloodbank_APP
    depends_on:
      - db
    # volumes:
    #   - ~/.composer-docker/cache:/root/.composer/cache:delegated
    #   - ./app/:/app:delegated
    #   - ./logs/apache:/var/log/apache2
    ports:
      - '8010:80'

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: bloodbank_PMA
    restart: always
    ports:
      - "8020:80"